### ISSUE TITLE
Flag 684-3xx for "multi-racial people (Hispanic/Latina/e/o)"

### ISSUE THREAD

**Issue by nataliesus** [MollyMcEvilley/LSASampleCode#1170]
Hi @JulesABrown ,

### Upload URL
https://hdxsandbox.abtsites.com/dataset/296/warning

### Flag 684
![image](https://github.com/HMIS/LSASampleCode/assets/28144855/528de855-814c-4e59-a018-4181f37448f0)

### Issue
According to the Spec (section 10.4) Population=70 and ReportRow=55 is for Multi-Racial & Hispanic/Latina/e/o (RaceEthnicity >=126, includes a 6 ):
![image](https://github.com/HMIS/LSASampleCode/assets/28144855/0eb7e737-47f2-4756-b1d9-2a93681352f7)

[Python logic for the LSAPerson version] needs correction because it close but not exactly the same as for Population=69 (Multi-Racial (not Hispanic/Latina/e/o)) not for  Population=70

Could you please take a look?

Thank you!
Natalie

**Comment by nataliesus** [comment]
Please notice Flag 684-4xx and Flag 684-9xx have the same issue with Multi-Racial & Hispanic/Latina/e/o conditions:
![image](https://github.com/HMIS/LSASampleCode/assets/28144855/49409b23-47e3-4f38-bf4c-4de7aa27ae73)
![image](https://github.com/HMIS/LSASampleCode/assets/28144855/9c4a6d28-7286-4169-a6de-a013f6ca63d5)

**Comment by JulesABrown** [comment]
We agree and have put in a ticket to fix the issue. We will notify you when the fix is made.

**Comment by JulesABrown** [comment]
Fix has been pushed to Sandbox - please check.

**Comment by nataliesus** [comment]
Hi @JulesABrown ,

I've made a new upload - https://hdxsandbox.abtsites.com/dataset/331/flag-report - and I still see 684-xxx flags (there are 28 entries of these flags)
![image](https://github.com/HMIS/LSASampleCode/assets/28144855/755debc9-c0c6-4d7a-b3a1-8ab7c91285c8)

![image](https://github.com/HMIS/LSASampleCode/assets/28144855/3823d901-c98e-4943-9917-50c310358b90)
![image](https://github.com/HMIS/LSASampleCode/assets/28144855/61bb34fc-a8a3-4c73-a319-f697371e7745)

Could you please take a look?

Thank you!
Natalie

**Comment by JulesABrown** [comment]
This has now been resolved
