### ISSUE TITLE
Discrepancy due to change in Step 3.4.4

### ISSUE THREAD

**Issue by evaripatis** [MollyMcEvilley/LSASampleCode#1202]
Logic for Step 3.4.4, in the sample code, was changed from:
```
min(case when dv.DomesticViolenceSurvivor = 1 and dv.CurrentlyFleeing = 1 then 1
when dv.DomesticViolenceSurvivor = 1 and dv.CurrentlyFleeing = 0 then 2 
when dv.DomesticViolenceSurvivor = 1 then 3
when dv.DomesticViolenceSurvivor = 0 then 10
when dv.DomesticViolenceSurvivor in (8,9) then 98
else null end)
```
To:
```
min(case when dv.DomesticViolenceSurvivor = 1 and dv.CurrentlyFleeing = 1 then 1
when dv.DomesticViolenceSurvivor = 1 and dv.CurrentlyFleeing = 0 then 2
when dv.DomesticViolenceSurvivor = 1 then 3
when dv.DomesticViolenceSurvivor = 0 then 10
else 98 end)
``` 
By this logic, it appears that the following two individuals should have a DVStatus value of 98, rather than Null in tlsa_Enrollment: PersonalIDs 687373 and 708167.  This would lead to them having a DVStatus value of 98, rather than 99, in tlsa_Person.  The sample output for tlsa_Enrollment has them with a value of Null and tlsa_Person has them with a value of 99.

**Comment by MollyMcEvilley** [comment]
This has been fixed with a refresh of the temp table export.

**Comment by evaripatis** [comment]
FYI, I had found 5 other individuals.  I will check with the refreshed data and let you know if I still see them.

**Comment by evaripatis** [comment]
All instances resolved.  Thank you.
